[package]
name = "undetected_geckodriver"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = "0.9.3"
thirtyfour = { version = "0.35.0", features = ["tokio-multi-threaded"] }
tokio = { version = "1.44.2", features = ["full"] }
serde_json = "1.0.140"
rand = "0.9.0"
